// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParksClient.Models;

namespace ParksClient.Migrations
{
    [DbContext(typeof(ParksClientContext))]
    partial class ParksClientContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("ParksClient.Models.Park", b =>
                {
                    b.Property<int>("ParkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ParkName")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("ParkId");

                    b.ToTable("Parks");

                    b.HasData(
                        new
                        {
                            ParkId = 1,
                            ParkName = "Matilda"
                        },
                        new
                        {
                            ParkId = 2,
                            ParkName = "Rexie"
                        },
                        new
                        {
                            ParkId = 3,
                            ParkName = "Matilda"
                        },
                        new
                        {
                            ParkId = 4,
                            ParkName = "Pip"
                        },
                        new
                        {
                            ParkId = 5,
                            ParkName = "Bartholomew"
                        });
                });

            modelBuilder.Entity("ParksClient.Models.State", b =>
                {
                    b.Property<int>("StateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("StatePopulation")
                        .HasColumnType("int");

                    b.Property<string>("StateTitle")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25) CHARACTER SET utf8mb4");

                    b.HasKey("StateId");

                    b.ToTable("States");

                    b.HasData(
                        new
                        {
                            StateId = 1,
                            StatePopulation = 1,
                            StateTitle = "Matilda"
                        },
                        new
                        {
                            StateId = 2,
                            StatePopulation = 2,
                            StateTitle = "Rexie"
                        },
                        new
                        {
                            StateId = 3,
                            StatePopulation = 3,
                            StateTitle = "Matilda"
                        },
                        new
                        {
                            StateId = 4,
                            StatePopulation = 4,
                            StateTitle = "Pip"
                        },
                        new
                        {
                            StateId = 5,
                            StatePopulation = 5,
                            StateTitle = "Bartholomew"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
