// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParksClient.Models;

namespace ParksClient.Migrations
{
    [DbContext(typeof(ParksClientContext))]
    partial class ParksClientContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("ParksClient.Models.Park", b =>
                {
                    b.Property<int>("ParkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ParkName")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<bool>("ParkNational")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("StateId")
                        .HasColumnType("int");

                    b.HasKey("ParkId");

                    b.HasIndex("StateId");

                    b.ToTable("Parks");

                    b.HasData(
                        new
                        {
                            ParkId = 1,
                            ParkName = "Yosemite",
                            ParkNational = true,
                            StateId = 1
                        },
                        new
                        {
                            ParkId = 2,
                            ParkName = "Joshua Tree",
                            ParkNational = true,
                            StateId = 1
                        },
                        new
                        {
                            ParkId = 3,
                            ParkName = "Olympic National",
                            ParkNational = true,
                            StateId = 3
                        },
                        new
                        {
                            ParkId = 4,
                            ParkName = "Cedar Lake",
                            ParkNational = true,
                            StateId = 4
                        },
                        new
                        {
                            ParkId = 5,
                            ParkName = "Big Spring State",
                            ParkNational = false,
                            StateId = 2
                        });
                });

            modelBuilder.Entity("ParksClient.Models.State", b =>
                {
                    b.Property<int>("StateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("StatePopulation")
                        .HasColumnType("int");

                    b.Property<string>("StateTitle")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25) CHARACTER SET utf8mb4");

                    b.HasKey("StateId");

                    b.ToTable("States");

                    b.HasData(
                        new
                        {
                            StateId = 1,
                            StatePopulation = 1,
                            StateTitle = "California"
                        },
                        new
                        {
                            StateId = 2,
                            StatePopulation = 2,
                            StateTitle = "Texas"
                        },
                        new
                        {
                            StateId = 3,
                            StatePopulation = 3,
                            StateTitle = "Washington"
                        },
                        new
                        {
                            StateId = 4,
                            StatePopulation = 4,
                            StateTitle = "Oregon"
                        },
                        new
                        {
                            StateId = 5,
                            StatePopulation = 5,
                            StateTitle = "Nevada"
                        });
                });

            modelBuilder.Entity("ParksClient.Models.Park", b =>
                {
                    b.HasOne("ParksClient.Models.State", "States")
                        .WithMany("Parks")
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("States");
                });

            modelBuilder.Entity("ParksClient.Models.State", b =>
                {
                    b.Navigation("Parks");
                });
#pragma warning restore 612, 618
        }
    }
}
